dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod: github.com/otelwasm/otelwasm/wasmexporter v0.88.0

processors:
  - gomod: github.com/otelwasm/otelwasm/wasmprocessor v0.88.0

receivers:
  - gomod: github.com/otelwasm/otelwasm/wasmreceiver v0.88.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0

replaces:
  - github.com/otelwasm/otelwasm/wasmprocessor => ../wasmprocessor
  - github.com/otelwasm/otelwasm/wasmexporter => ../wasmexporter
  - github.com/otelwasm/otelwasm/wasmplugin => ../wasmplugin
  - github.com/otelwasm/otelwasm/wasmreceiver => ../wasmreceiver
