receivers:
  wasm/otlpreceiver:
    path: "./otlpreceiver.wasm"
    plugin_config:
      protocols:
        http:
          endpoint: "localhost:4318"

processors:
  wasm/attributesprocessor:
    path: "./attributesprocessor.wasm"
    plugin_config:
      actions:
        - key: "new_attribute"
          value: "new_value"
          action: "insert"

exporters:
  wasm/otlphttpexporter:
    path: ./otlphttpexporter.wasm
    plugin_config:
      sending_queue:
      enabled: false

service:
  pipelines:
    logs:
      receivers: [wasm/otlpreceiver]
      processors: [wasm/attributesprocessor:]
      exporters: [wasm/otlphttpexporter]
