name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: wasmplugin/go.mod
          cache: true
          cache-dependency-path: wasmplugin/go.mod

      - name: Run formatter
        run: make format

      - name: Check diff
        run: |
          git add -N .
          git diff --exit-code

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: [wasmreceiver, wasmprocessor, wasmexporter, guest]
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Go
        uses: actions/setup-go@0aaccfd150d50ccaeb58ebd88d36e91967a5f35b # v5.4.0
        with:
          go-version-file: ${{ matrix.module }}/go.mod
          cache: true
          cache-dependency-path: ${{ matrix.module }}/go.mod

      - name: Set up QEMU
        uses: docker/setup-qemu-action@29109295f81e9208d7d86ff1c6c12d2833863392 # v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0

      - name: Build wasm examples
        run: |
          make copy-wasm-examples
      - name: Run tests
        run: cd ${{ matrix.module }} && go test -tags docker -v ./... -coverprofile=coverage.out
